### ISSUE TITLE
Issue while using basic authentication

### ISSUE THREAD

**Issue by GodsonPattudurai** [play-rconf/play-rconf-http#7]
Hi Team,

I am getting below issue while i was trying to get configuration using basic authentication. But its working fine without basic auth.

! @7k2oin5pg - Internal server error, for (GET) [/] ->

"play.api.UnexpectedException: Unexpected exception[BadPath: Invalid path 'http://user-server:password@localhost:8080/server/config/dev.conf': java.io.IOException]
        at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:214)
        at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:144)
        at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:304)
        at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:189)
        at akka.stream.impl.fusing.MapAsync$$anon$30.onPush(Ops.scala:1262)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:523)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:409)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:599)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:480)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:574)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:664)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
        at akka.actor.ActorCell.invoke(ActorCell.scala:579)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.typesafe.config.ConfigException$BadPath: Invalid path 'http://user-server:password@localhost:8080/server/config/dev.conf': java.io.IOException
        at io.playrconf.provider.HttpProvider.loadData(HttpProvider.java:114)
        at io.playrconf.ApplicationLoaderScala.$anonfun$processAllProviders$3(ApplicationLoaderScala.scala:137)
        at io.playrconf.ApplicationLoaderScala.$anonfun$processAllProviders$3$adapted(ApplicationLoaderScala.scala:117)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at io.playrconf.ApplicationLoaderScala.processAllProviders(ApplicationLoaderScala.scala:117)
        at io.playrconf.ApplicationLoaderScala.builder(ApplicationLoaderScala.scala:68)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:22)
        at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:193)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:22)
        at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:185)
        ... 23 common frames omitted
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: http://user-server:password@localhost:8080/server/config/dev.conf
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
        at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
        at com.typesafe.config.impl.Parseable$ParseableURL.reader(Parseable.java:555)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:231)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
        at com.typesafe.config.ConfigFactory.parseURL(ConfigFactory.java:656)
        at io.playrconf.provider.HttpProvider.loadData(HttpProvider.java:95)
        ... 32 common frames omitted
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: http://user-server:password@localhost:8080/server/config/dev.conf
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
        at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
        at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3061)
        at java.net.URLConnection.getContentType(URLConnection.java:511)
        at com.typesafe.config.impl.Parseable$ParseableURL.reader(Parseable.java:545)
        ... 38 common frames omitted

Could you please help us to find the rootcause.

Thanks in advance.

**Comment by thibaultmeyer** [comment]
Hello,

I have released a new version of the project (_21.06_) that supports Auth-Basic authentication. The README has been updated for the usage instructions.
